/** The canonical source's rolling-lineup rules, also used for its saved prompt. */
export const APOLLO_SOURCE_INSTRUCTIONS = `Apollo Theatre, 19 East College Street, Oberlin, OH 44074, operated by Cleveland Cinemas.

These rules replace older Apollo examples and generic title/venue grouping, description-date, and duplicate-report rules.

READ THE SCHEDULE
Read the WHOLE configured Veezi sessions page within the source's lookahead. Read every film and every visible show date; do not assume a fixed number of films. The date and film tabs repeat the same data. Ignore unrelated MovieTheater metadata and use the venue details above. Consolidate repeated rows by actual film title, preserving sequel numbers and each film's own earliest and latest visible dates. A movie that began earlier and still has future showings is ongoing, not expired. Never mistake the rolling page's first visible day for a verified premiere. Skip films with no showings after today. Do not invent dates beyond the visible schedule.

ANNOUNCEMENT WINDOWS
Classify each film at today's community-local date before making windows. A film with a verified opening on or before today is current; a film whose verified opening is after today is upcoming. Future opening films are Coming Soon even when their dates are adjacent to a current film—no schedule gap is required. Active tracking of an earlier opening keeps a current film current when the theater is closed today and its next visible showing is later. A completed prior run does not make a later reopening current. Never put a future-only film in a Playing Now lineup.

Look forward from tomorrow for Playing Now display windows. Make a new window on the day AFTER a current film's last visible date, keeping each window's exact current lineup. Ordinary closed days inside a film's observed run do not create another announcement. For Coming Soon, present only the film or films at the nearest future opening date; later presales wait for a later run instead of flooding the review queue. Use each future film's opening date as its display session. Example: today Sep 5; a current film runs through Sep 9 and another opens Sep 10. Playing Now contains only the current film through Sep 9, and the Sep 10 film is Coming Soon even though the dates are adjacent. Use the full calendar year from the run context; handle Dec/Jan correctly.

CONTENT
Every payload is eventType an, category Film (5), sponsor Apollo Theater, locationType ph2, location 19 East College Street, Oberlin, OH 44074, placeName Apollo Theatre. Titles are Playing Now at the Apollo or Coming Soon at the Apollo. description is the film lineup, not generic prose: Film title: Sep 1 to Sep 9 . Other film: Sep 1 to Sep 9; Coming Soon uses Film title: opens Sep 10. Use each film's OWN dates, not the shared window bounds. Dates are allowed here in the short description only. Leave extendedDescription empty. Preserve every film title, including sequel numbers; if a lineup exceeds 200 characters, flag it rather than dropping a film or truncating a title. Sessions are the announcement's window, first day 00:00 through last day 23:59, ISO local wall-clock strings. For a Coming Soon entry use its verified opening date as the display session; do not invent an earlier posting window.

IMAGES AND LINKS
Give imageUrls with one real poster for each film in the lineup; the server combines them. Prefer official posters; the source's own Veezi posters are valid fallbacks. contactEmail apollo@clevelandcinemas.com; phone 440-774-3920; website https://www.clevelandcinemas.com/our-locations/x03gq-apollo-theatre/. calendarSourceUrl and a Buy Tickets button use the configured Veezi listing. These shared theater/listing URLs are NOT identities for individual announcements.

DUPLICATE EVIDENCE
Return every complete Apollo announcement in events, including ones already in either inventory. Keep duplicates empty. The server checks the actual film lineup, announcement kind, individual film dates, and covered display window. Never collapse different lineups because they share a title, venue, URL, poster, or some films. An unchanged lineup inside an already-covered window can be a duplicate. Changed films, changed film end/open dates, and newly uncovered windows require review; do not silently discard them or extend old content. Preserve complete descriptions, dates and images so a reviewer can audit every comparison.`;
